export const getEdgesToNode = (nodeId) => {
    const edges = {
        '8': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2a-6', source: '2a', sourceHandle: 'right', target: '6', targetHandle: 'left' },
            { id: 'e6-7', source: '6', sourceHandle: 'right', target: '7', targetHandle: 'left' },
            { id: 'e7-8', source: '7', sourceHandle: 'bottom', target: '8', targetHandle: 'top' },
        ],
        '43': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e10-40', source: '10', sourceHandle: 'right', target: '40', targetHandle: 'left' },
            { id: 'e40-41', source: '40', sourceHandle: 'bottom', target: '41', targetHandle: 'top' },
            { id: 'e41-43', source: '41', sourceHandle: 'bottom', target: '43', targetHandle: 'top' },
        ],
        '44': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e10-40', source: '10', sourceHandle: 'right', target: '40', targetHandle: 'left' },
            { id: 'e40-42', source: '40', sourceHandle: 'bottom', target: '42', targetHandle: 'top' },
            { id: 'e42-44', source: '42', sourceHandle: 'bottom', target: '44', targetHandle: 'top', label: "X" },
        ],
        '21': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17a-19', source: '17a', sourceHandle: 'right', target: '19', targetHandle: 'left' },
            { id: 'e19-20', source: '19', sourceHandle: 'bottom', target: '20', targetHandle: 'top' },
            { id: 'e20-21', source: '20', sourceHandle: 'bottom', target: '21', targetHandle: 'top', label: "X" },
        ],
        '16': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e11-12', source: '11', sourceHandle: 'left', target: '12', targetHandle: 'right' },
            { id: 'e12-14', source: '12', sourceHandle: 'bottom', target: '14', targetHandle: 'top' },
            { id: 'e14-16', source: '14', sourceHandle: 'bottom', target: '16', targetHandle: 'top' },
        ],
        '15': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e11-12', source: '11', sourceHandle: 'left', target: '12', targetHandle: 'right' },
            { id: 'e12-13', source: '12', sourceHandle: 'bottom', target: '13', targetHandle: 'top' },
            { id: 'e13-15', source: '13', sourceHandle: 'bottom', target: '15', targetHandle: 'top' },
        ],
        '5': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2b-3', source: '2b', sourceHandle: 'left', target: '3', targetHandle: 'right' },
            { id: 'e3-4', source: '3', sourceHandle: 'left', target: '4', targetHandle: 'right' },
            { id: 'e4-5', source: '4', sourceHandle: 'bottom', target: '5', targetHandle: 'top' },
        ],
        '23': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-22', source: '18', sourceHandle: 'bottom', target: '22', targetHandle: 'top' },
            { id: 'e22-23', source: '22', sourceHandle: 'bottom', target: '23', targetHandle: 'top' },
        ],
        '25': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-24', source: '18', sourceHandle: 'bottom', target: '24', targetHandle: 'top' },
            { id: 'e24-25', source: '24', sourceHandle: 'bottom', target: '25', targetHandle: 'top' },
        ],
        '27': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-26', source: '18', sourceHandle: 'bottom', target: '26', targetHandle: 'top' },
            { id: 'e26-27', source: '26', sourceHandle: 'bottom', target: '27', targetHandle: 'top' },
        ],
        '29': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-28', source: '18', sourceHandle: 'bottom', target: '28', targetHandle: 'top' },
            { id: 'e28-29', source: '28', sourceHandle: 'bottom', target: '29', targetHandle: 'top', label: "X" },
        ],
        '31': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-30', source: '18', sourceHandle: 'bottom', target: '30', targetHandle: 'top' },
            { id: 'e30-31', source: '30', sourceHandle: 'bottom', target: '31', targetHandle: 'top' },
        ],
        '33': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-32', source: '18', sourceHandle: 'bottom', target: '32', targetHandle: 'top' },
            { id: 'e32-33', source: '32', sourceHandle: 'bottom', target: '33', targetHandle: 'top' },
        ],
        '35': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-34', source: '18', sourceHandle: 'bottom', target: '34', targetHandle: 'top' },
            { id: 'e34-35', source: '34', sourceHandle: 'bottom', target: '35', targetHandle: 'top' },
        ],
        '37': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-36', source: '18', sourceHandle: 'bottom', target: '36', targetHandle: 'top' },
            { id: 'e36-37', source: '36', sourceHandle: 'bottom', target: '37', targetHandle: 'top' },
        ],
        '59': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e9-45', source: '9', sourceHandle: 'bottom', target: '45', targetHandle: 'top' },
            { id: 'e45-56', source: '45', sourceHandle: 'bottom', target: '56', targetHandle: 'top' },
            { id: 'e56-57', source: '56', sourceHandle: 'bottom', target: '57', targetHandle: 'top' },
            { id: 'e57-59', source: '57', sourceHandle: 'bottom', target: '59', targetHandle: 'top' },
        ],
        '55': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e9-45', source: '9', sourceHandle: 'bottom', target: '45', targetHandle: 'top' },
            { id: 'e47-49', source: '47', sourceHandle: 'left', target: '49', targetHandle: 'right' },
            { id: 'e50-53', source: '50', sourceHandle: 'bottom', target: '53', targetHandle: 'top' },
            { id: 'e53-54', source: '53', sourceHandle: 'bottom', target: '54', targetHandle: 'top' },
            { id: 'e54-55', source: '54', sourceHandle: 'bottom', target: '55', targetHandle: 'top' },
        ],
        '52': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e9-45', source: '9', sourceHandle: 'bottom', target: '45', targetHandle: 'top' },
            { id: 'e47-49', source: '47', sourceHandle: 'left', target: '49', targetHandle: 'right' },
            { id: 'e48-51', source: '48', sourceHandle: 'left', target: '51', targetHandle: 'right' },
            { id: 'e51-52', source: '51', sourceHandle: 'bottom', target: '52', targetHandle: 'top', label: "X" },
        ],
        '39': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-11', source: '2c', sourceHandle: 'bottom', target: '11', targetHandle: 'top' },
            { id: 'e17-18', source: '17', sourceHandle: 'bottom', target: '18', targetHandle: 'top' },
            { id: 'e18-38', source: '18', sourceHandle: 'bottom', target: '38', targetHandle: 'top' },
            { id: 'e38-39', source: '38', sourceHandle: 'bottom', target: '39', targetHandle: 'top' },
        ],
        '60': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e9-45', source: '9', sourceHandle: 'bottom', target: '45', targetHandle: 'top' },
            { id: 'e45-56', source: '45', sourceHandle: 'bottom', target: '56', targetHandle: 'top' },
            { id: 'e56-58', source: '56', sourceHandle: 'bottom', target: '58', targetHandle: 'top' },
            { id: 'e58-60', source: '58', sourceHandle: 'bottom', target: '60', targetHandle: 'top' },
        ],
        '65': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e9-45', source: '9', sourceHandle: 'bottom', target: '45', targetHandle: 'top' },
            { id: 'e45-61', source: '45', sourceHandle: 'bottom', target: '61', targetHandle: 'top' },
            { id: 'e61-62', source: '61', sourceHandle: 'bottom', target: '62', targetHandle: 'top' },
            { id: 'e62-64', source: '62', sourceHandle: 'bottom', target: '64', targetHandle: 'top' },
            { id: 'e64-65', source: '64', sourceHandle: 'bottom', target: '65', targetHandle: 'top' },
        ],
        '67': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e9-45', source: '9', sourceHandle: 'bottom', target: '45', targetHandle: 'top' },
            { id: 'e45-61', source: '45', sourceHandle: 'bottom', target: '61', targetHandle: 'top' },
            { id: 'e61-66', source: '61', sourceHandle: 'bottom', target: '66', targetHandle: 'top' },
            { id: 'e66-67', source: '66', sourceHandle: 'bottom', target: '67', targetHandle: 'top' },
        ],
        '69': [
            { id: 'e1-2c', source: '1', sourceHandle: 'bottom', target: '2c', targetHandle: 'top' },
            { id: 'e2c-10', source: '2c', sourceHandle: 'bottom', target: '10', targetHandle: 'top' },
            { id: 'e9-45', source: '9', sourceHandle: 'bottom', target: '45', targetHandle: 'top' },
            { id: 'e45-61', source: '45', sourceHandle: 'bottom', target: '61', targetHandle: 'top' },
            { id: 'e61-63', source: '61', sourceHandle: 'bottom', target: '63', targetHandle: 'top' },
            { id: 'e63-68', source: '63', sourceHandle: 'bottom', target: '68', targetHandle: 'top' },
            { id: 'e68-69', source: '68', sourceHandle: 'bottom', target: '69', targetHandle: 'top', label: "X" },
        ],
    };
    return edges[nodeId] || [];
};
